#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

docker run -it \
  -p 8080:8080 \
  --device=/dev/video0 \
  --name=${PROJECT_NAME} \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --rm \
  ${PROJECT_NAME}