ARDUINO_DIR = /usr/share/arduino
BOOTLOADER_PARENT = /usr/share/arduino/bootloaders
ARDUINO_PORT = /dev/ttyACM0
BOARD_TAG = uno
USER_LIB_PATH = /arduinoLibraries/
ARDUINO_LIBS = /Wire /ZumoShield

include /usr/share/arduino/Arduino.mk
