#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config.sh

echo "Building Docker image..."
docker build -t ${PROJECT_NAME} ${PROJECT_ROOT}

echo "Upload and clean..."
${PROJECT_ROOT}/script/run sh -c 'cd arduino && make clean && make upload'
